server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdatabase
    username: trackeruser
    password: usersecret
  flyway:
    enabled: true